package plugin

import (
	"fmt"
	"time"

	"google.golang.org/protobuf/compiler/protogen"
)

// Generator is the main entry point for the protoc-gen-go-jsonschema plugin.
// It coordinates the overall code generation process: deciding which messages
// generate schemas, building their schema models, and printing the output file.
type Generator struct {
	// Version is the plugin version used to generate this file
	Version string
}

// generateFile creates a Go source file containing JSON Schema generation code
// for all targeted messages in the given proto file.
//
// The generation process:
//  1. Checks file-level options to determine the default generation behavior
//  2. Collects all messages that should generate schemas (respecting options),
//     plus any message defined here that another file in the request forced
//  3. Analyzes reference cycles to decide each message's mode (inline vs $defs)
//  4. Builds the schema model for each message (all schema decisions)
//  5. Prints the models into the output file (all Go-syntax decisions)
//
// targets is the request-wide collection result (collectTargets).
// Returns nil if no messages in the file require schema generation.
func (gr *Generator) generateFile(gen *protogen.Plugin, file *protogen.File, targets targetSet) (*protogen.GeneratedFile, error) {
	// --- Determine Generation Scope ---
	// Collect messages that should generate schemas, including their
	// dependencies (cross-package messages and Google types included, so the
	// reference graph is complete). The visited map prevents processing the
	// same message twice.
	visited := make(map[string]bool)
	targetMessages := getMessagesWithForce(file.Messages, fileGeneratesAll(file), false, visited)

	// A message defined here that a sibling file forced — typically a
	// `generate = false` dependency referenced from that file — generates
	// here too, with its own dependencies: the sibling's _WithDefs call must
	// resolve, and only this file can emit the function.
	for _, forced := range forcedLocalMessages(file.Messages, targets, visited) {
		targetMessages = append(targetMessages, getMessagesWithForce([]*protogen.Message{forced}, true, true, visited)...)
	}

	// --- Filter to only messages DEFINED in THIS proto file ---
	//
	// When multiple proto files share the same Go package and import each other
	// (or import the same shared protos), generating by Go package would emit
	// duplicate function definitions. Messages from other proto files are only
	// referenced by their _WithDefs function name — they are generated in their
	// own file. Google types are the exception: they are generated in the file
	// where they're referenced, as standalone functions with a file prefix.
	var localMessages []*protogen.Message
	var googleTypeMessages []*protogen.Message
	for _, msg := range targetMessages {
		// Note: Use Path() not FullName() - FullName() returns the package name for files
		if msg.Desc.ParentFile().Path() == file.Desc.Path() {
			localMessages = append(localMessages, msg)
		} else if isGoogleType(msg) {
			googleTypeMessages = append(googleTypeMessages, msg)
		}
	}

	// Skip file generation entirely if no local messages or Google types need
	// schemas. This avoids creating empty or import-only files.
	if len(localMessages) == 0 && len(googleTypeMessages) == 0 {
		return nil, nil
	}

	// --- Create Output File ---
	filename := file.GeneratedFilenamePrefix + "_jsonschema.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Write file header with generation metadata.
	g.P("// Code generated by https://github.com/alis-exchange/protoc-gen-go-jsonschema. DO NOT EDIT.")
	g.P("// ")
	g.P(fmt.Sprintf("// Source: %s", file.Desc.Path()))
	g.P(fmt.Sprintf("// Plugin version: %s", gr.Version))
	g.P("// ")
	g.P(fmt.Sprintf("// Generated on: %s UTC", time.Now().UTC().Format("2006-01-02 15:04:05")))

	g.P()
	g.P(fmt.Sprintf("package %s", file.GoPackageName))

	// Additional imports may be added automatically by protogen when
	// QualifiedGoIdent is used during printing.
	g.P("import (")
	g.P("\"github.com/google/jsonschema-go/jsonschema\"")
	g.P(")")
	g.P()

	// --- Analyze, Build and Print Message Schemas ---
	// The cycle analysis decides each message's mode (inline vs $defs) before
	// any model is built; see analyzeCycles.
	ctx := &schemaContext{
		filePrefix: fileNamePrefix(file),
		cycles:     analyzeCycles(targetMessages),
	}
	printer := &schemaPrinter{g: g}
	for _, msg := range append(localMessages, googleTypeMessages...) {
		model, err := buildMessageSchema(msg, ctx)
		if err != nil {
			return nil, err
		}
		printer.printMessageSchema(model)
		g.P()
	}

	return g, nil
}
