package plugintest

import (
	"strings"
	"testing"

	"github.com/alis-exchange/protoc-gen-go-jsonschema/plugin"
	"github.com/stretchr/testify/suite"
)

// PluginGeneratorTestSuite contains tests for the Generate function's output.
// Message-collection, naming, and schema-model internals are covered by
// in-package tests in plugin/ — the schema model is the plugin's internal seam
// and is tested through its own interface there.
type PluginGeneratorTestSuite struct {
	PluginTestSuite
}

// TestPluginGeneratorSuite runs the PluginGeneratorTestSuite.
func TestPluginGeneratorSuite(t *testing.T) {
	suite.Run(t, new(PluginGeneratorTestSuite))
}

// TestGenerate tests the main Generate function.
func (s *PluginGeneratorTestSuite) TestGenerate() {
	err := plugin.Generate(s.Plugin(), "test")
	s.Require().NoError(err, "Generate failed")

	// Check the response
	resp := s.Plugin().Response()
	s.Require().Empty(resp.GetError(), "Generate response error")

	// Verify we got generated files
	s.Require().NotEmpty(resp.File, "Expected generated files")

	// Check that the generated file has the expected suffix
	foundJsonSchema := false
	for _, f := range resp.File {
		if strings.HasSuffix(f.GetName(), "_jsonschema.pb.go") {
			foundJsonSchema = true

			// Verify the content is not empty
			s.NotEmpty(f.GetContent(), "Generated file content is empty")

			// Verify the content has expected structure
			content := f.GetContent()
			s.Contains(content, "package ", "Missing package declaration")
			s.Contains(content, "JsonSchema()", "Missing JsonSchema method")
			s.Contains(content, "jsonschema.Schema", "Missing jsonschema.Schema type")
		}
	}

	s.True(foundJsonSchema, "Expected a file with _jsonschema.pb.go suffix")
}

// TestGenerateNoFiles tests Generate with no files to generate.
func (s *PluginGeneratorTestSuite) TestGenerateNoFiles() {
	// Create a new plugin with no files to generate
	emptyPlugin := createTestPlugin(s.T(), s.FileDescriptorSet(), []string{})

	err := plugin.Generate(emptyPlugin, "test")
	s.Require().NoError(err, "Generate failed")

	resp := emptyPlugin.Response()
	s.Require().Empty(resp.GetError(), "Generate response error")

	// Should have no generated files
	s.Empty(resp.File, "Expected no generated files")
}

// TestGeneratedCodeStructure tests the structure of generated code.
func (s *PluginGeneratorTestSuite) TestGeneratedCodeStructure() {
	contents := s.RunGenerate()

	for name, content := range contents {
		s.Run(name, func() {
			s.Contains(content, "Code generated by", "Missing generation header comment")
			s.Contains(content, "DO NOT EDIT", "Missing DO NOT EDIT comment")
			s.Contains(content, "package ", "Missing package declaration")
			s.Contains(content, "jsonschema", "Missing jsonschema import")

			hasMethod := strings.Contains(content, "func (x *") && strings.Contains(content, "JsonSchema()")
			hasGoogleTypeFunction := strings.Contains(content, "google_protobuf_") && strings.Contains(content, "_JsonSchema()")
			s.True(hasMethod || hasGoogleTypeFunction, "Missing JsonSchema method or Google type function pattern")

			s.Contains(content, "_JsonSchema_WithDefs(defs map[string]*jsonschema.Schema)",
				"Missing _JsonSchema_WithDefs function pattern")

			hasObjectType := strings.Contains(content, `Type:`) && strings.Contains(content, `"object"`)
			s.True(hasObjectType, "Missing object type in schema")
			s.Contains(content, "Properties:", "Missing Properties in schema")
		})
	}
}

// TestGeneratedCodeForSpecificMessages tests generated code for specific message types.
func (s *PluginGeneratorTestSuite) TestGeneratedCodeForSpecificMessages() {
	content := s.GetGeneratedContent()

	tests := []struct {
		name     string
		contains []string
	}{
		{"User message", []string{"User_JsonSchema_WithDefs", `"id"`, `"name"`, `"email"`}},
		{"Address message", []string{"Address_JsonSchema_WithDefs", `"street"`, `"city"`}},
		{"ComprehensiveUser message", []string{"ComprehensiveUser_JsonSchema_WithDefs"}},
		{"Enum handling", []string{"Enum: []any{"}},
		{"Array handling", []string{`"array"`, "Items:"}},
		{"Map handling", []string{"AdditionalProperties:"}},
	}

	for _, tt := range tests {
		s.Run(tt.name, func() {
			for _, expected := range tt.contains {
				s.Contains(content, expected, "Expected content to contain %q", expected)
			}
		})
	}
}

// TestOneOfHandling tests oneof field handling in generated code.
func (s *PluginGeneratorTestSuite) TestOneOfHandling() {
	content := s.GetGeneratedContent()
	s.Contains(content, "OneOf", "Generated code should contain OneOf constraints")
	s.Contains(content, `schema.Properties["Identifier"]`,
		"User message oneofs should use PascalCase wrapper properties")

	cuSection := extractGoFuncSection(content, "ComprehensiveUser_JsonSchema_WithDefs")
	s.Require().NotEmpty(cuSection, "ComprehensiveUser_JsonSchema_WithDefs not found")
	s.NotContains(cuSection, `schema.AllOf`,
		"ComprehensiveUser should not have root-level AllOf oneof constraints")
}

// TestGoogleTypesHandling tests Google type handling in generated code.
func (s *PluginGeneratorTestSuite) TestGoogleTypesHandling() {
	content := s.GetGeneratedContent()

	hasGoogleTypeFunctions := strings.Contains(content, "google_protobuf_") &&
		strings.Contains(content, "_JsonSchema()")

	if strings.Contains(content, "Timestamp") || strings.Contains(content, "Duration") {
		s.True(hasGoogleTypeFunctions, "Google types should generate standalone functions")
	}
}

// TestBytesFieldHandling tests bytes field handling.
func (s *PluginGeneratorTestSuite) TestBytesFieldHandling() {
	content := s.GetGeneratedContent()
	s.Contains(content, `ContentEncoding: "base64"`, "Expected base64 content encoding for bytes fields")
}

// TestInt64FieldHandling tests int64 field handling.
func (s *PluginGeneratorTestSuite) TestInt64FieldHandling() {
	content := s.GetGeneratedContent()
	s.Contains(content, `^-?[0-9]+$`, "Expected numeric string pattern for int64 fields")
}
